/*

 MAP_FRITZ.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : fritztile.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_fritzboxWidth 20
#define map_fritzboxHeight 18
#define map_fritzboxBank 0

extern unsigned char map_fritzbox[];

/* End of MAP_FRITZ.H */
